package com.xuechuan.xcedu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xuechuan.xcedu.db.DownVideoDb;
import com.xuechuan.xcedu.db.UpDataNoteDb;
import com.xuechuan.xcedu.db.UserInfomDb;

import com.xuechuan.xcedu.db.DownVideoDbDao;
import com.xuechuan.xcedu.db.UpDataNoteDbDao;
import com.xuechuan.xcedu.db.UserInfomDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downVideoDbDaoConfig;
    private final DaoConfig upDataNoteDbDaoConfig;
    private final DaoConfig userInfomDbDaoConfig;

    private final DownVideoDbDao downVideoDbDao;
    private final UpDataNoteDbDao upDataNoteDbDao;
    private final UserInfomDbDao userInfomDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downVideoDbDaoConfig = daoConfigMap.get(DownVideoDbDao.class).clone();
        downVideoDbDaoConfig.initIdentityScope(type);

        upDataNoteDbDaoConfig = daoConfigMap.get(UpDataNoteDbDao.class).clone();
        upDataNoteDbDaoConfig.initIdentityScope(type);

        userInfomDbDaoConfig = daoConfigMap.get(UserInfomDbDao.class).clone();
        userInfomDbDaoConfig.initIdentityScope(type);

        downVideoDbDao = new DownVideoDbDao(downVideoDbDaoConfig, this);
        upDataNoteDbDao = new UpDataNoteDbDao(upDataNoteDbDaoConfig, this);
        userInfomDbDao = new UserInfomDbDao(userInfomDbDaoConfig, this);

        registerDao(DownVideoDb.class, downVideoDbDao);
        registerDao(UpDataNoteDb.class, upDataNoteDbDao);
        registerDao(UserInfomDb.class, userInfomDbDao);
    }
    
    public void clear() {
        downVideoDbDaoConfig.clearIdentityScope();
        upDataNoteDbDaoConfig.clearIdentityScope();
        userInfomDbDaoConfig.clearIdentityScope();
    }

    public DownVideoDbDao getDownVideoDbDao() {
        return downVideoDbDao;
    }

    public UpDataNoteDbDao getUpDataNoteDbDao() {
        return upDataNoteDbDao;
    }

    public UserInfomDbDao getUserInfomDbDao() {
        return userInfomDbDao;
    }

}
